### ISSUE TITLE
Battery staying charged

### ISSUE THREAD

**Issue by screberg** [precision-sustainable-ag/NodeGateway#1]
The size of the battery seems insufficient for the task.  Can someone check the data files to see how many times the battery dipped below the minimum voltage and turned off a node?  Should we attempt a higher voltage battery.  The board can handle anything up to 12 volts.

**Comment by paularamo** [comment]
This is an old issue but we can follow the identification power problem with this issue. I will measure power once we will reinstall the previous Firmware version. I wanted to tag @hschomberg and @alondrathompson to involve more in the GitHub issues.
