### ISSUE TITLE
Communication issue

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/NodeGateway#2]

**Comment by paularamo** [comment]
@saseehav wrote an issue to notify a communication problem. She wrote, "I don't know if my node is communicating with my gateway on Farm LAB".

 We can follow this issue to document the problem solution about communication.

**Comment by paularamo** [comment]
@alondrathompson, @hschomberg, and @screberg we could follow this issue to document the communication solution.

**Comment by screberg** [comment]
We need to circle back on what to do with this repository.  The acclima repo is where we work, but we also need something public for our collaborators.  Discuss at next meeting
