### ISSUE TITLE
Installation and comunication Nodes and Gateways (NCSU Yard)

### ISSUE THREAD

**Issue by paularamo** [precision-sustainable-ag/NodeGateway#7]
Hello, everybody,

I wanted to share with you certain things I found today by reinstalling and reconfiguring the nodes and gateways with the firmware developed for CROWN.

I installed 4 nodes, two new and two old. All sensors are old and were used last season. We have installed cover crops and bare nodes in our yard. The two cover crop nodes are new cards and the bare nodes are old. 

One of the cover crop nodes has all the sensors working. a, b, c, z, h, t. For the other cover crops node I found several problems:

1. It is not possible to configure the 6 sensors and there are errors in humidity and temperature sensors (999). I found a large network of small spiders inside the humidity sensor and the temperature sensor was very dirty and maybe with some damage in the PCB.
2. I disconnected all sensors and start by connecting a,b,c z. It was possible to configure and test them. OK
3. I connected the humidity sensor and it was possible to configure it together with the previous one. OK
4. I connected the temperature sensor. And the z sensor and the humidity sensor were not recognized. Failed.
5. This node is running without a temperature sensor.
6. For bare nodes, all worked properly.
7. We don't see the correct activity in hologram. Something is sending by gateway but it could be garbage.

**Comment by paularamo** [comment]
I resynchronized the nodes-gateways today. And here are some comments.

Difficulty in synchronization.

The first node synchronizes well and there is a message of successful synchronization in both Node and Gateway. When I try to synchronize the second node, the gateway returns successful synchronization and the node returns synchronization failed. This problem was constant in both sets Nodes-Gateway. After many attempts appeared successful synchronization on the side of the node.

Difficulty in time synchronization.

Following the protocol of "Time Synchronization in the Field" ON Nodes - ON gateways. The status LEDs have remained on without achieving communication between nodes and gateway. This was constant in both sets Nodes-Gateways. I decided to check one of them with Arduino's Serial Monitor and apparently was able to ping the nodes and get information from them. The other set is still waiting for a connection.

@alondrathompson How much time it is necessary to wait for the time synchronization?

@saseehav Could you check if NC27 and NC28 are sending understandable information through hologram?

**Comment by alondrathompson** [comment]
4. I connected the temperature sensor. And the z sensor and the humidity sensor were not recognized. Failed.

--> Does it still fail if you try a different temperature sensor?

When I try to synchronize the second node, the gateway returns successful synchronization and the node returns synchronization failed. 

--> I've seen this before too and may have to do with the radio settings (timeouts). I think what happens is that the Gateway gets a response from the Node, but the Node misses the Gateway's acknowledgement and thinks that the synchronization failed. We'll have to look at the timeouts and retries in the firmware.

How much time it is necessary to wait for the time synchronization?

--> The nodes will wait for 2 hrs to hear from the Gateway. The Gateway will spend 2hrs/ # of Nodes minutes trying to make contact with each node in the order that the radio IDs were input into the menu. If the synchronization will all the nodes is successful, the Gateway will send a message to all nodes that it is done and they will all break out of the synchronization routine and move on to the measurement routine. Usually, if the synchronization is successful it will take only a few seconds.

I'll be trying to set up some nodes today and I'll report back with any issues I run into.

**Comment by saseehav** [comment]
@pjramg 

NC 27 I see put this data every hour:
This message starting at 10am: 
085(96) Gateway awake at 12/19/2019 15:1. Synced to Nodes: 35 Missed Nodes: 11 .
and then this every hour:
085~2019-12-19_18:04:47_UTC~4086~6~2288
NC 28 I don't see at all

**Comment by screberg** [comment]
Added @saseehav
